name: flutter_easy_animations
description: "This library provides a variety of convenient Flutter animation effects."
version: 0.0.1
homepage: https://flutter-online.top
repository: https://github.com/jacklee1995/flutter_easy_animations
auth:
  name: Jcak Lee
  email: 291148484@163.com
  home: http://thispage.tech
environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

screenshots:
  - description: "EasyAnimations Logo."
    path: assets/easy_animations.png
  - description: "example for AnimateStyles class."
    path: assets/example_easyanimationanimatestylesvVU5ImxxqS.gif


flutter:

