name: flutter_easy_animations
description: "Animate.css for Flutter. All 97 effects with the original names and keyframes."
version: 1.0.0
homepage: https://flutter-online.top
repository: https://github.com/jacklee1995/flutter_easy_animations
issue_tracker: https://github.com/jacklee1995/flutter_easy_animations/issues

topics:
  - animation
  - animations
  - ui
  - transitions
  - animate-css

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

screenshots:
  - description: "flutter_easy_animations logo."
    path: assets/easy_animations.png

flutter:
